---
defaults:
  - wandb: defaults
  - hydra: defaults
  - cam_embd: defaults
  - _self_
general:
  device: 0
  random_seed: 0
  num_devices: 1
  mixed_precision: false
data:
  training_resolution: 128
  subset: -1
  input_images: 1
  origin_distances: false
  erase_occlusion: false
opt:
  iterations: 800001
  base_lr: 0.00005
  batch_size: 8
  betas:
    - 0.9
    - 0.999
  loss: l2
  imgs_per_obj: 4
  ema: 
    use: true
    update_every: 10
    update_after_step: 100
    beta: 0.9999
  lambda_lpips: 0.0
  pretrained_ckpt: null
  mask_p: 0.0
  freeze_decoder: false
  weight_loss:
    enabled: false
    offset: 1.0
    global_coef: 0.05
    occluded_area: 1.0
    outline: 1.0
  compute_loss_on_condition: false
  gan:
    base_lr: 0.00005

model:
  max_sh_degree: 1
  inverted_x: false
  inverted_y: true
  name: SingleUNet
  opacity_scale: 1.0
  opacity_bias: -2.0
  scale_bias: 0.02
  scale_scale: 0.003
  xyz_scale: 0.1
  xyz_bias: 0.0
  depth_scale: 1.0
  depth_bias: 0.0
  network_without_offset: false
  network_with_offset: true
  attention_resolutions:
  - 16
  num_blocks: 4
  cross_view_attention: true
  base_dim: 128
  isotropic: false
  input_channels: 4
  extend_bottleneck:
    enabled: false
    feats:
      repo: "facebookresearch/dinov2"
      model: "dinov2_vitl14"
      multiplier: 14
    concat_mode: 2
    cinterm_unet_multiplier: 1
gan:
  enabled: true
  sample_p: 0.5
  noise_sigma: 0.1
  
logging:
  ckpt_iterations: 1000
  val_log: 5000
  loss_log: 10
  loop_log: 5000
  render_log: 1000
